services:
  api:
    build: .
    container_name: github-search-api
    ports:
      - "8000:8000"
    environment:
      - TOKEN_FOR_GITHUB_API=${TOKEN_FOR_GITHUB_API}
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
